name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Product viewer tests
      id: product-viewer-tests
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Product viewer tests
        setup-command: npm install
        command: npm test
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PRODUCT-VIEWER-TESTS_RESULTS: "${{steps.product-viewer-tests.outputs.result}}"
      with:
        runners: product-viewer-tests
